from . import res_company
from . import res_config_settings
from . import res_partner
from . import product_category
from . import product_template
from . import sale_order
from . import account_move
from . import whub_notice_sync_engine
from . import whub_notice_sync_log
from . import whub_notice_sync_wizard
from . import wizard_homologation
from . import whub_notice_resolve_wizard
