from . import res_config_settings
from . import tafel_config
from . import tafel_setup_wizard
from . import tafel_provider_option
from . import tafel_provider_config
from . import tafel_provider_payment_method
from . import tafel_payment_method_map
from . import tafel_journal_config
from . import tafel_field_map
from . import tafel_custom_field
from . import account_move
from . import tafel_fiscal_document
from . import tafel_fiscal_document_attempt
from . import tafel_provider_setup_wizard
