{
    'name': 'Facturación Electrónica',
    'version': '18.0.1.14.5',
    'summary': 'Facturación Electrónica para Venezuela',
    'category': 'Accounting',
    'author': 'Total Aplicaciones',
    'website': 'https://www.totalaplicaciones.com',
    'depends': ['base', 'base_setup', 'account'],
    'external_dependencies': {
        'python': ['requests'],
    },
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'views/tafel_setup_wizard_views.xml',
        'views/tafel_config_views.xml',
        'views/tafel_provider_config_views.xml',
        'views/tafel_provider_setup_wizard_views.xml',
        'views/tafel_field_map_views.xml',
        'views/tafel_custom_field_views.xml',
        'views/tafel_fiscal_document_views.xml',
        'views/account_move_views.xml',
        'views/tafel_menu.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
